name: Release Package

on:
  push:
    branches: [ main, beta ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      issues: read

    steps:
      - uses: actions/checkout@v3
        id: checkout
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        id: install_node
        with:
          node-version: 20.x

      - name: Install Deps
        id: install_deps
        run: yarn install --frozen-lockfile

      - name: Release
        id: release
        run: |
          yarn ci:token
          yarn release
        env:
          NODE_ENV_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          ORG: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
